
title: "AI talks"
description: "Learning, creating, and thinking in the world of Artificial Intelligence"
baseurl: "" 
url: "https://sarasaber1367.github.io"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

author:
  name: "Sara Saber"
  avatar: "/assets/images/avatar.png"
  bio: "Master student | AI learner"
